// Screens
export const SCREEN_NAME = {
  LOADING: 'LoadingScreen',
  HOME: 'HomeScreen',
  CALCULATOR: 'Calculator',
  MY_WALLET: 'MyWallet',
  MY_WISHES: 'MyWishes',
  MY_SAVINGS: 'MySavings',
  PROFILE: 'Profile',
  NEW_WISH: 'NewWish',
  FULFILL_WISH: 'FulfillWish',
  BUY: 'Buy',
  ADD_REMOVE: 'AddRemove',
  ADD_REMOVE_WALLET: 'AddRemoveWallet',
  ADD_REMOVE_SAVINGS: 'AddRemoveSavings',
  ADD_REMOVE_BILLS: 'AddRemoveBills',
  ADD_REMOVE_COINS: 'AddRemoveCoins',
  ABOUT: 'About',
  SURVEY: 'Survey',
  INFORMATION: 'Information',
  HOW_TO_USE_APP: 'HowToUseApp',
  SIGN_LANGUAGE: 'SignLanguage',
  WISHES_FULLFILLED: 'WishesFulfilled',
  SAVINGS_BUY: 'SavingsBuy',
  WALLET_BUY: 'WalletBuy',
  WALLET_MANUAL_PAYMENT: 'WalletManualPayment',
  SAVINGS_MANUAL_PAYMENT: 'SavingsManualPayment',
  CALCULATOR_NAV: 'CalculatorNav',
  WISHES_NAV: 'WishesNav',
  INFORMATION_NAV: 'InformationNav',
};

// Title navigation style
export const NAVIGATION_TITLE = {
  HOME: 'INICO',
  CALCULATOR: 'CALCULADORA',
  MY_WALLET: 'MI BILLETERA',
  MY_WISHES: 'MIS DESEOS',
  WISHES: 'DESEOS',
  WISHES_FULLFILLED: 'DESEOS CUMPLIDOS',
  MY_SAVINGS: 'MIS AHORROS',
  PROFILE: 'PERFIL',
  NEW_WISH: 'AGREGAR DESEO',
  EDIT_WISH: 'EDITAR DESEO',
  FULFILL_WISH: 'CUMPLIR DESEO',
  BUY: 'COMPRAR',
  ADD_REMOVE: 'AGREGAR/QUITAR',
  ADD_REMOVE_WALLET: 'AGREGAR / QUITAR EN BILLETERA',
  ADD_REMOVE_SAVINGS: 'AGREGAR / QUITAR EN MIS AHORROS',
  ADD_REMOVE_BILLS: 'BILLETES',
  ADD_REMOVE_COINS: 'MONEDAS',
  ADD_REMOVE_BILLS_SAVINGS: 'BILLETES',
  ADD_REMOVE_COINS_SAVINGS: 'MONEDAS',
  ABOUT: 'SOBRE NOSOTROS',
  INFO: 'INFORMACION',
  SURVEY: 'ENCUESTA',
  HOW_TO_USE_APP: '¿COMO USAR LA APLICACION?',
  SIGN_LANGUAGE: 'LENGUAJE DE SEÑAS',
  LOGOS: 'LOGOS',
  SAVINGS_BUY: 'COMPRAR CON AHORROS',
  WALLET_BUY: 'COMPRAR CON BILLETERA',
  WALLET_MANUAL_PAYMENT: 'PAGO MANUAL BILLETERA',
  SAVINGS_MANUAL_PAYMENT: 'PAGO MANUAL AHORROS',
  BILLETES: 'BILLETES',
  MONEDAS: 'MONEDAS',
};

export const NAVIGATION_ICONS = {
  ADD_REMOVE: 'hand-holding-usd',
};

// Title for navigation tab
export const TABS_NAME = {
  HOME: 'HomeScreenTab',
  CALCULATOR: 'CalculatorTab',
  MY_WALLET: 'MyWalletTab',
  MY_WISHES: 'MyWishesTab',
  MY_SAVINGS: 'MySavingsTab',
  PROFILE: 'ProfileTab',
  NEW_WISH: 'NewWishTab',
  FULFILL_WISH: 'FulfillWishTab',
  BUY: 'BuyTab',
  ADD_REMOVE: 'AddRemoveTab',
  ADD_REMOVE_WALLET: 'AddRemoveWalletTab',
  ABOUT: 'AboutTab',
  INFORMATION: 'InformationTab',
  SAVINGS_BUY: 'SavingsBuyTab',
  WALLET_BUY: 'WalletBuyTab',
};

export const labels = {
  attention: 'Atención',
  permissions: {
    gallery: 'No hay permisos para acceder a la galería de fotos',
    camera: 'No hay permisos para acceder a la cámara de fotos',
  },
  insertName: 'Escribí tu nombre',
  aboutScreen: {
    dane: 'Dane',
    descripton:
      'El proyecto Dane propone llevar adelante una revolución en la manera de enseñarles contenidos a personas con discapacidad. Creamos aplicaciones móviles e integramos la tecnología informática a la educación, aportando contenidos académicos y de la vida cotidiana. El objetivo del proyecto es ayudar a la inclusión de las personas con discapacidad y promover en la sociedad la cultura de la inclusión',
    coordination: 'Coordinación del proyecto',
    idea: 'Idea y contenido',
    ideaText: 'A definir',
    development: 'Desarrollo',
    acknowledgment: 'Agradecimientos',
    acknowledgmentText: 'A definir',
    license: 'Licencia GNU V3',
    licenseLink: 'https://tinc.org.ar/licencias/',
  },
  surveyScreen: {
    complete: '¡Gracias por completar la encuesta!',
    completeAgain: 'VOLVER A REALIZARLA',
    error: 'Ocurrió un error al cargar la encuesta',
    again: 'Vuelva a intentarlo',
  },
};
